In [ ]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import cv2
from google.colab import drive
from tqdm import tqdm
import dlib
#!pip install mediapipe
#import mediapipe as mp
import seaborn as sns
from scipy.fftpack import fft2, fftshift
from scipy import ndimage
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
from tqdm import tqdm
from PIL import Image
from time import time
from sklearn.datasets import fetch_olivetti_faces
from sklearn.decomposition import PCA
from skimage.feature import hog
from imutils import face_utils
import argparse
import imutils
import cv2
!wget http://dlib.net/files/shape_predictor_68_face_landmarks.dat.bz2
!bunzip2 shape_predictor_68_face_landmarks.dat.bz2

!pip install insightface onnxruntime
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import roc_curve, auc
from sklearn.preprocessing import label_binarize
from sklearn.model_selection import GridSearchCV
from sklearn.neural_network import MLPClassifier


from insightface.app import FaceAnalysis
import warnings
warnings.filterwarnings('ignore')

drive.mount('/content/drive')

--2025-12-08 02:06:04--  http://dlib.net/files/shape_predictor_68_face_landmarks.dat.bz2
Resolving dlib.net (dlib.net)... 107.180.26.78
Connecting to dlib.net (dlib.net)|107.180.26.78|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://dlib.net/files/shape_predictor_68_face_landmarks.dat.bz2 [following]
--2025-12-08 02:06:04--  https://dlib.net/files/shape_predictor_68_face_landmarks.dat.bz2
Connecting to dlib.net (dlib.net)|107.180.26.78|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 64040097 (61M)
Saving to: ‘shape_predictor_68_face_landmarks.dat.bz2’

shape_predictor_68_ 100%[===================>]  61.07M  15.1MB/s    in 5.0s

2025-12-08 02:06:10 (12.2 MB/s) - ‘shape_predictor_68_face_landmarks.dat.bz2’ saved [64040097/64040097]

Collecting insightface
  Downloading insightface-0.7.3.tar.gz (439 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 439.5/439.5 kB 7.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting onnxruntime
  Downloading onnxruntime-1.23.2-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.1 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from insightface) (2.0.2)
Collecting onnx (from insightface)
  Downloading onnx-1.20.0-cp312-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from insightface) (4.67.1)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from insightface) (2.32.4)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from insightface) (3.10.0)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from insightface) (11.3.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from insightface) (1.16.3)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from insightface) (1.6.1)
Requirement already satisfied: scikit-image in /usr/local/lib/python3.12/dist-packages (from insightface) (0.25.2)
Requirement already satisfied: easydict in /usr/local/lib/python3.12/dist-packages (from insightface) (1.13)
Requirement already satisfied: cython in /usr/local/lib/python3.12/dist-packages (from insightface) (3.0.12)
Requirement already satisfied: albumentations in /usr/local/lib/python3.12/dist-packages (from insightface) (2.0.8)
Requirement already satisfied: prettytable in /usr/local/lib/python3.12/dist-packages (from insightface) (3.17.0)
Collecting coloredlogs (from onnxruntime)
  Downloading coloredlogs-15.0.1-py2.py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.12/dist-packages (from onnxruntime) (25.9.23)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from onnxruntime) (25.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from onnxruntime) (5.29.5)
Requirement already satisfied: sympy in /usr/local/lib/python3.12/dist-packages (from onnxruntime) (1.14.0)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from albumentations->insightface) (6.0.3)
Requirement already satisfied: pydantic>=2.9.2 in /usr/local/lib/python3.12/dist-packages (from albumentations->insightface) (2.12.3)
Requirement already satisfied: albucore==0.0.24 in /usr/local/lib/python3.12/dist-packages (from albumentations->insightface) (0.0.24)
Requirement already satisfied: opencv-python-headless>=4.9.0.80 in /usr/local/lib/python3.12/dist-packages (from albumentations->insightface) (4.12.0.88)
Requirement already satisfied: stringzilla>=3.10.4 in /usr/local/lib/python3.12/dist-packages (from albucore==0.0.24->albumentations->insightface) (4.2.3)
Requirement already satisfied: simsimd>=5.9.2 in /usr/local/lib/python3.12/dist-packages (from albucore==0.0.24->albumentations->insightface) (6.5.3)
Collecting humanfriendly>=9.1 (from coloredlogs->onnxruntime)
  Downloading humanfriendly-10.0-py2.py3-none-any.whl.metadata (9.2 kB)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->insightface) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->insightface) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->insightface) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->insightface) (1.4.9)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->insightface) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib->insightface) (2.9.0.post0)
Requirement already satisfied: typing_extensions>=4.7.1 in /usr/local/lib/python3.12/dist-packages (from onnx->insightface) (4.15.0)
Requirement already satisfied: ml_dtypes>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from onnx->insightface) (0.5.4)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prettytable->insightface) (0.2.14)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->insightface) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->insightface) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->insightface) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->insightface) (2025.11.12)
Requirement already satisfied: networkx>=3.0 in /usr/local/lib/python3.12/dist-packages (from scikit-image->insightface) (3.6)
Requirement already satisfied: imageio!=2.35.0,>=2.33 in /usr/local/lib/python3.12/dist-packages (from scikit-image->insightface) (2.37.2)
Requirement already satisfied: tifffile>=2022.8.12 in /usr/local/lib/python3.12/dist-packages (from scikit-image->insightface) (2025.10.16)
Requirement already satisfied: lazy-loader>=0.4 in /usr/local/lib/python3.12/dist-packages (from scikit-image->insightface) (0.4)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->insightface) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->insightface) (3.6.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy->onnxruntime) (1.3.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.9.2->albumentations->insightface) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.9.2->albumentations->insightface) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.9.2->albumentations->insightface) (0.4.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib->insightface) (1.17.0)
Downloading onnxruntime-1.23.2-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (17.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.4/17.4 MB 138.7 MB/s eta 0:00:00
Downloading coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.0/46.0 kB 3.5 MB/s eta 0:00:00
Downloading onnx-1.20.0-cp312-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (18.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.1/18.1 MB 108.2 MB/s eta 0:00:00
Downloading humanfriendly-10.0-py2.py3-none-any.whl (86 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.8/86.8 kB 7.6 MB/s eta 0:00:00
Building wheels for collected packages: insightface
  Building wheel for insightface (pyproject.toml) ... done
  Created wheel for insightface: filename=insightface-0.7.3-cp312-cp312-linux_x86_64.whl size=1071349 sha256=d59c3c651c4703a39bc0fd69bc9f0fdfbca88100ba60beb1859a52f7fd309300
  Stored in directory: /root/.cache/pip/wheels/73/3c/e2/6d4815e8a8b33a2006554d65ce0d1f973e768f4c7a222fa675
Successfully built insightface
Installing collected packages: humanfriendly, onnx, coloredlogs, onnxruntime, insightface
Successfully installed coloredlogs-15.0.1 humanfriendly-10.0 insightface-0.7.3 onnx-1.20.0 onnxruntime-1.23.2
Mounted at /content/drive

In [ ]:
path = "drive/MyDrive/datasci281/"
train_dir = path + "train/"
test_dir = path + "test/"
emotion_names = ['angry', 'disgust', 'fear', 'happy', 'sad', 'surprise', 'neutral']
df_train = pd.DataFrame(columns=['path', 'expression'])
df_test = pd.DataFrame(columns=['path', 'expression'])

for expression in os.listdir(train_dir):
    dir_ = train_dir + expression
    for img_name in os.listdir(dir_):
        img_path = dir_ + '/' + img_name
        df_train = pd.concat([df_train, pd.DataFrame({'path': [img_path], 'expression': [expression]})], ignore_index=True)
# df_train.head()
for expression in os.listdir(test_dir):
    dir_ = test_dir + expression
    for img_name in os.listdir(dir_):
        img_path = dir_ + '/' + img_name
        df_test = pd.concat([df_test, pd.DataFrame({'path': [img_path], 'expression': [expression]})], ignore_index=True)

In [ ]:
df_train.head()

                                                path expression
0  drive/MyDrive/datasci281/train/angry/Training_...      angry
1  drive/MyDrive/datasci281/train/angry/Training_...      angry
2  drive/MyDrive/datasci281/train/angry/Training_...      angry
3  drive/MyDrive/datasci281/train/angry/Training_...      angry
4  drive/MyDrive/datasci281/train/angry/Training_...      angry

In [ ]:
print("Train shape:", df_train.shape)
print("Test shape:", df_test.shape)

Train shape: (28709, 2)
Test shape: (7178, 2)

In [ ]:
df_train['expression'].value_counts()

expression
happy       7215
neutral     4965
sad         4830
fear        4097
angry       3995
surprise    3171
disgust      436
Name: count, dtype: int64

In [ ]:
df_test['expression'].value_counts()

expression
happy       1774
sad         1247
neutral     1233
fear        1024
angry        958
surprise     831
disgust      111
Name: count, dtype: int64

In [ ]:
#Ecode the labels
le = LabelEncoder()
df_train['label'] = le.fit_transform(df_train['expression'])
df_test['label']  = le.transform(df_test['expression'])

In [ ]:
df_train.head()

                                                path expression  label
0  drive/MyDrive/datasci281/train/angry/Training_...      angry      0
1  drive/MyDrive/datasci281/train/angry/Training_...      angry      0
2  drive/MyDrive/datasci281/train/angry/Training_...      angry      0
3  drive/MyDrive/datasci281/train/angry/Training_...      angry      0
4  drive/MyDrive/datasci281/train/angry/Training_...      angry      0

In [ ]:

detector = dlib.get_frontal_face_detector()
predictor = dlib.shape_predictor("shape_predictor_68_face_landmarks.dat")
app = FaceAnalysis(name="buffalo_l")
app.prepare(ctx_id=0, det_size=(224, 224))


def normalize_landmarks(pts):
    pts_centered = pts - pts[30]  # nose tip
    eye_dist = np.linalg.norm(pts[36] - pts[45]) + 1e-6
    pts_norm = pts_centered / eye_dist
    return pts_norm.flatten()  # (136,)


def extract_landmarks_from_path(img_path, detector, predictor):
    img = cv2.imread(img_path)
    if img is None:
        raise RuntimeError(f"Could not load {img_path}")

    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    gray = cv2.resize(gray, (96, 96))   # upscale from FER2013 (48×48)

    rects = detector(gray, 1)

    if len(rects) == 0:
        # fallback: whole image
        h, w = gray.shape
        rects = [dlib.rectangle(0, 0, w, h)]

    shape = predictor(gray, rects[0])

    pts = np.array(
        [[shape.part(i).x, shape.part(i).y] for i in range(68)],
        dtype=np.float32
    )

    return pts



def build_landmark_dataset(df, detector, predictor):
    X = []
    y = []

    for _, row in tqdm(df.iterrows(), total=len(df), desc="Landmarks"):
        try:
            pts = extract_landmarks_from_path(row["path"], detector, predictor)
            feat = normalize_landmarks(pts)
        except:
            feat = np.zeros(136, dtype=np.float32)

        X.append(feat)
        y.append(row["expression"])

    return np.array(X, dtype=np.float32), np.array(y)


def load_fer2013_hog(data_dir, ppc=8, cpb=2, ori=9):
    X = []
    y = []
    image_paths = []

    for label, emotion in enumerate(emotion_names):
        emotion_path = os.path.join(data_dir, emotion)
        if not os.path.isdir(emotion_path):
            continue

        for f in tqdm(os.listdir(emotion_path), desc=emotion):
            path = os.path.join(emotion_path, f)
            img = Image.open(path).convert('L').resize((96, 96))
            arr = np.array(img)

            feat = hog(
                arr,
                orientations=ori,
                pixels_per_cell=(ppc, ppc),
                cells_per_block=(cpb, cpb),
                block_norm="L2-Hys",
                feature_vector=True
            )

            X.append(feat)
            y.append(label)
            image_paths.append(path)

    return np.array(X, dtype=np.float32), np.array(y), image_paths



def extract_insightface_embedding(path):
    img = cv2.imread(path)
    img = cv2.resize(gray, (96, 96))
    if img is None:
        return np.zeros(512, dtype=np.float32)

    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    faces = app.get(img)

    if len(faces) == 0:
        return np.zeros(512, dtype=np.float32)

    return np.array(faces[0].embedding, dtype=np.float32)


def subsample(X, y, n=5000):
    if len(X) <= n:
        return X, y
    idx = np.random.choice(len(X), size=n, replace=False)
    return X[idx], y[idx]

download_path: /root/.insightface/models/buffalo_l
Downloading /root/.insightface/models/buffalo_l.zip from https://github.com/deepinsight/insightface/releases/download/v0.7/buffalo_l.zip...

100%|██████████| 281857/281857 [00:02<00:00, 94384.08KB/s]

Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /root/.insightface/models/buffalo_l/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /root/.insightface/models/buffalo_l/2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /root/.insightface/models/buffalo_l/det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /root/.insightface/models/buffalo_l/genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /root/.insightface/models/buffalo_l/w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (224, 224)

# Training data

In [ ]:
X_hog, y, image_paths = load_fer2013_hog(train_dir) # add rrename vars

In [ ]:
# --- LANDMARKS ---
X_land, _ = build_landmark_dataset(df_test, detector, predictor)

In [ ]:
# --- INSIGHTFACE ---
X_emb = np.vstack([extract_insightface_embedding(p) for p in tqdm(image_paths)])

In [ ]:
# --- FINAL CONCATENATION ---
X_final = np.hstack([X_hog, X_land, X_emb])

print("Final Feature Shape:", X_final.shape)

In [ ]:
print("HOG", X_hog.shape)
print("Landmarks", X_land.shape)
print("Insightface", X_emb.shape )

In [ ]:
np.save("drive/MyDrive/datasci281/X_train_embeddings.npy", X_final)
np.save("drive/MyDrive/datasci281/y_train_embeddings.npy", y)
np.save("drive/MyDrive/datasci281/X_train_hog.npy", X_hog)
np.save("drive/MyDrive/datasci281/X_train_land.npy", X_land)
np.save("drive/MyDrive/datasci281/X_train_arcface.npy", X_emb)

# Test Data

In [ ]:
X_hog, y, image_paths = load_fer2013_hog(test_dir) # add rrename vars

angry: 100%|██████████| 958/958 [00:16<00:00, 58.10it/s]
disgust: 100%|██████████| 111/111 [00:02<00:00, 39.11it/s]
fear: 100%|██████████| 1024/1024 [00:17<00:00, 58.57it/s]
happy: 100%|██████████| 1774/1774 [00:54<00:00, 32.62it/s]
sad: 100%|██████████| 1247/1247 [00:51<00:00, 24.26it/s]
surprise: 100%|██████████| 831/831 [00:13<00:00, 60.50it/s]
neutral: 100%|██████████| 1233/1233 [00:23<00:00, 52.45it/s]

In [ ]:
# --- LANDMARKS ---
X_land, _ = build_landmark_dataset(df_test, detector, predictor)

Landmarks: 100%|██████████| 7178/7178 [01:08<00:00, 104.06it/s]

In [ ]:
# --- INSIGHTFACE ---
X_emb = np.vstack([extract_insightface_embedding(p) for p in tqdm(image_paths)])

100%|██████████| 7178/7178 [17:13<00:00,  6.95it/s]

In [ ]:
# --- FINAL CONCATENATION ---
X_final = np.hstack([X_hog, X_land, X_emb])

print("Final Feature Shape:", X_final.shape)

Final Feature Shape: (7178, 1548)

In [ ]:
print("HOG", X_hog.shape)
print("Landmarks", X_land.shape)
print("Insightface", X_emb.shape )

HOG (7178, 900)
Landmarks (7178, 136)
Insightface (7178, 512)

In [ ]:
np.save("drive/MyDrive/datasci281/X_test_embeddings.npy", X_final)
np.save("drive/MyDrive/datasci281/y_test_embeddings.npy", y)
np.save("drive/MyDrive/datasci281/X_test_hog.npy", X_hog)
np.save("drive/MyDrive/datasci281/X_test_land.npy", X_land)
np.save("drive/MyDrive/datasci281/X_test_arcface.npy", X_emb)

## Summary

This was created as the getting of the embeddins for the landmarks and the arcface required a hugeamount of time and resources. Saving the embedings in a numpy allowed us to create hyperparamter tuning for various classifiers.